### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by shacker** [ozkatz/announce.js#4] opened 2012-05-31 18:31 UTC
I work on a project that can only integrate tools and libraries with an appropriate license, but this project doesn't appear to have any license at all. Can you add one please? Our project is compatible with these licenses (bottom of page). Not that that should sway  your licensing decision: :)

https://confluence.sakaiproject.org/display/LIC/3rd+Party+Licenses+and+Software

**Comment by ozkatz** [comment] 2012-05-31 18:34
Hi, this is a duplicate of:  https://github.com/ozkatz/announce.js/issues/3
In any case, the license will very likely be MIT (which is compatible with the list you have provided).

**Closed as completed by ozkatz** 2012-05-31 18:34 UTC

**Comment by ozkatz** [comment] 2012-06-01 00:59
just as an update: an MIT license section has been added to the README. hope you find the project useful!

**Comment by shacker** [comment] 2012-06-01 18:39
Many thanks! Forwarded to team.
